plugins {
    alias(libs.plugins.android.application).apply(false)
    alias(libs.plugins.firebase.crashlytics).apply(false)
    alias(libs.plugins.jetbrains.compose.compiler).apply(false)
    alias(libs.plugins.jetbrains.serialization).apply(false)
    alias(libs.plugins.google.services).apply(false)
}

def localProperties = new Properties().tap {
    load(new FileInputStream(file("local.properties")))
}

allprojects {
    ext.localProperties = localProperties
}
