apply from: 'tools.gradle'
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'

android {
    compileSdk = libs.versions.android.sdk.compile.get().toInteger()

    buildFeatures {
        buildConfig = true
    }
    def fileProviderAuthority = "com.scurab.android.zumpareader.fileprovider"
    defaultConfig {
        namespace "com.scurab.android.zumpareader"
        applicationId "com.scurab.zumpareader"
        buildConfigField "String", "BUILD_DETAIL", "\"build-" + getDate() + ",git-" + gitSha() + "\""
        buildConfigField "String", "Authority", "\"" + fileProviderAuthority + "\""
        minSdk = libs.versions.android.sdk.min.get().toInteger()
        targetSdk = libs.versions.android.sdk.target.get().toInteger()
        versionCode 68
        versionName "3.3.0"
        manifestPlaceholders = [authority: fileProviderAuthority]
        multiDexEnabled true
    }

    signingConfigs {
        release {
            keyAlias localProperties.get('releaseKeyAlias')
            keyPassword localProperties.get('releaseKeyPassword')
            storePassword localProperties.get('releaseStorePassword')
            var keystorePath = localProperties.get("releaseKeyStore")
            if (keystorePath != null) {
                // without this check, builds fail for debug if 'releaseKeyStore' is missing
                storeFile file(keystorePath)
            }
        }
    }

    buildTypes {
        debug {
            versionNameSuffix "-" + getDate()
            minifyEnabled false
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility = libs.versions.jvmtarget.get()
        targetCompatibility = libs.versions.jvmtarget.get()
    }

    kotlinOptions {
        jvmTarget = libs.versions.jvmtarget.get().toInteger()
        freeCompilerArgs = freeCompilerArgs + ["-Xcontext-receivers"]
    }
}


task(depsize) {
    doLast {
        def size = 0;
        configurations._debugApk.collect { it.length() / (1024 * 1024) }.each { size += it }
        println "Total dependencies size: ${Math.round(size * 100) / 100} Mb"

        configurations
                ._debugApk
                .sort { -it.length() }
                .each { println "${it.name} : ${Math.round(it.length() / (1024) * 100) / 100} kb" }
    }
}

dependencies {
    //compile fileTree(dir: 'libs', include: ['*.jar'])
    implementation(libs.kotlin.stdlib)
    implementation(libs.kotlinx.coroutines)
    implementation(platform(libs.firebase.bom))
    implementation(libs.bundles.firebase)
    implementation(libs.bundles.android.base)
    implementation(libs.jsoup)
    implementation(libs.bundles.okhttp)

    implementation libs.bundles.retrofit

    implementation libs.swipy

    implementation libs.picasso

    implementation libs.kotson
    implementation libs.otto

    implementation libs.rxjava
    implementation libs.rxandroid
    implementation libs.rxbinding
    implementation libs.bundles.rxlifecycle

    implementation libs.bundles.fresco

    implementation libs.pinchtozoom

    testImplementation libs.junit4
    testImplementation libs.robolectric.base
    testImplementation libs.robolectric.shadows.support.v4
    testImplementation(libs.festandroid) {
        exclude module: 'support-v4'//some weird incompatibility issue
    }
    testImplementation libs.mockito
}
