apply from: 'tools.gradle'
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'

android {
    namespace = "com.scurab.android.zumpareader"
    compileSdk = libs.versions.android.sdk.compile.get().toInteger()

    buildFeatures {
        buildConfig = true
    }
    def fileProviderAuthority = "com.scurab.android.zumpareader.fileprovider"
    defaultConfig {
        applicationId = "com.scurab.zumpareader"
        buildConfigField "String", "BUILD_DETAIL", "\"build-" + getDate() + ",git-" + gitSha() + "\""
        buildConfigField "String", "Authority", "\"" + fileProviderAuthority + "\""
        minSdk = libs.versions.android.sdk.min.get().toInteger()
        targetSdk = libs.versions.android.sdk.target.get().toInteger()
        versionCode = 68
        versionName = "3.3.0"
        manifestPlaceholders = [authority: fileProviderAuthority]
        multiDexEnabled = true
    }

    signingConfigs {
        release {
            keyAlias = localProperties.get('releaseKeyAlias')
            keyPassword = localProperties.get('releaseKeyPassword')
            storePassword = localProperties.get('releaseStorePassword')
            var keystorePath = localProperties.get("releaseKeyStore")
            if (keystorePath != null) {
                // without this check, builds fail for debug if 'releaseKeyStore' is missing
                storeFile = file(keystorePath)
            }
        }
    }

    buildTypes {
        debug {
            versionNameSuffix = "-" + getDate()
            minifyEnabled = false
        }
        release {
            minifyEnabled = false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig = signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility = libs.versions.jvmtarget.get()
        targetCompatibility = libs.versions.jvmtarget.get()
    }
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget(libs.versions.jvmtarget.get())
    }
}

dependencies {
    //compile fileTree(dir: 'libs', include: ['*.jar'])
    implementation(libs.kotlin.stdlib)
    implementation(libs.kotlinx.coroutines)
    implementation(platform(libs.firebase.bom))
    implementation(libs.bundles.firebase)
    implementation(libs.bundles.android.base)
    implementation(libs.jsoup)
    implementation(libs.gson)
    implementation(libs.bundles.okhttp)

    implementation libs.bundles.retrofit

    implementation libs.swipy

    implementation libs.picasso

    implementation libs.kotson
    implementation libs.otto

    implementation libs.rxjava
    implementation libs.rxandroid
    implementation libs.rxbinding
    implementation libs.bundles.rxlifecycle

    implementation libs.bundles.fresco

    implementation libs.pinchtozoom
}
