apply from: 'tools.gradle'
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'

android {
    compileSdk = libs.versions.android.sdk.compile.get().toInteger()

    buildFeatures {
        buildConfig = true
    }
    def fileProviderAuthority = "com.scurab.android.zumpareader.fileprovider"
    defaultConfig {
        namespace "com.scurab.android.zumpareader"
        applicationId "com.scurab.zumpareader"
        buildConfigField "String", "BUILD_DETAIL", "\"build-" + getDate() + ",git-" + gitSha() + "\""
        buildConfigField "String", "Authority", "\"" + fileProviderAuthority + "\""
        minSdk = libs.versions.android.sdk.min.get().toInteger()
        targetSdk = libs.versions.android.sdk.target.get().toInteger()
        versionCode 66
        versionName "3.1.0"
        manifestPlaceholders = [authority: fileProviderAuthority]
        multiDexEnabled true
    }

    buildTypes {
        debug {
            versionNameSuffix "-" + getDate()
            minifyEnabled false
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility = libs.versions.jvmtarget.get()
        targetCompatibility = libs.versions.jvmtarget.get()
    }

    kotlinOptions {
        jvmTarget = libs.versions.jvmtarget.get().toInteger()
        freeCompilerArgs = freeCompilerArgs + ["-Xcontext-receivers"]
    }
}


task(depsize) {
    doLast {
        def size = 0;
        configurations._debugApk.collect { it.length() / (1024 * 1024) }.each { size += it }
        println "Total dependencies size: ${Math.round(size * 100) / 100} Mb"

        configurations
                ._debugApk
                .sort { -it.length() }
                .each { println "${it.name} : ${Math.round(it.length() / (1024) * 100) / 100} kb" }
    }
}

dependencies {
    //compile fileTree(dir: 'libs', include: ['*.jar'])
    implementation(libs.kotlin.stdlib)
    implementation(libs.kotlinx.coroutines)
    implementation(platform(libs.firebase.bom))
    ["crashlytics", "messaging"].forEach {
        implementation("com.google.firebase:firebase-$it-ktx")
    }
    implementation(libs.bundles.android.base)
    implementation(libs.jsoup)
    implementation(libs.bundles.okhttp)

    def retrofit = "2.4.0"
    implementation "com.squareup.retrofit2:retrofit:$retrofit"
    implementation "com.squareup.retrofit2:converter-gson:$retrofit"
    implementation "com.squareup.retrofit2:adapter-rxjava2:$retrofit"

    implementation 'com.github.orangegangsters:swipy:1.2.3@aar'

    implementation 'com.squareup.picasso:picasso:2.5.2'

    implementation 'com.github.salomonbrys.kotson:kotson:2.5.0'
    implementation 'com.squareup:otto:1.3.8'

    implementation "io.reactivex.rxjava2:rxjava:2.2.10"
    implementation 'io.reactivex.rxjava2:rxandroid:2.0.2'
    implementation 'com.jakewharton.rxbinding2:rxbinding:2.0.0'
    def trelo = "2.2.2"
    implementation "com.trello.rxlifecycle2:rxlifecycle:${trelo}"
    implementation "com.trello.rxlifecycle2:rxlifecycle-android:${trelo}"
    implementation "com.trello.rxlifecycle2:rxlifecycle-components:${trelo}"
    implementation "com.trello.rxlifecycle2:rxlifecycle-navi:${trelo}"

    // (Recommended) Add the Google Analytics dependency.
//    implementation 'com.google.firebase:firebase-analytics:17.6.0'

    // Add the Firebase Crashlytics dependency.
    //implementation 'com.crashlytics.sdk.android:crashlytics:17.2.2'

    def fresco = "1.14.2"
    implementation "com.facebook.fresco:fresco:${fresco}"
    implementation "com.facebook.fresco:animated-gif:${fresco}"

    implementation 'com.bogdwellers:pinchtozoom:0.1'

    testImplementation 'junit:junit:4.12'
    def robo = "3.3.1"
    testImplementation "org.robolectric:robolectric:$robo"
    testImplementation "org.robolectric:shadows-support-v4:$robo"
    testImplementation('com.squareup:fest-android:1.0.8') {
        exclude module: 'support-v4'//some weird incompatibility issue
    }
    testImplementation 'org.mockito:mockito-core:2.25.0'
}
